---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
  - name: debian-8.7
  - name: centos-7.3
  - name: fedora-24

suites:
  - name: default
    run_list:
      - recipe[bleemeo::default]
    attributes:
