AllCops:
  Exclude:
    - 'Berksfile'
    - 'Vagrantfile'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 80
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - test/**/*

Style/VariableName:
  EnforcedStyle: camelCase
Style/MethodName:
  EnforcedStyle: camelCase
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/CaseEquality:
  Severity: warning
Style/MultilineBlockChain:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/FileName:
  Enabled: false
